Repository ShopRunner/baleen, pull requests merged in 2019-12, with the labels that each got.

#86 Support Model classes that contain companion objects when generating DataDescriptions
  baleen-kotlin/baleen-kotlin-kapt/src/main/kotlin/com/shoprunner/baleen/kapt/DataClassExtensionBuilder.kt
  baleen-kotlin/baleen-kotlin-kapt/src/main/kotlin/com/shoprunner/baleen/kapt/DataDescriptionBuilder.kt
  baleen-kotlin/baleen-kotlin-kapt/src/test/kotlin/com/shoprunner/baleen/kotlin/kapt/test/BasicModelTest.kt
  baleen-kotlin/baleen-kotlin-kapt/src/test/kotlin/com/shoprunner/baleen/kotlin/kapt/test/Models.kt
Labels: bug

#81 Generate data classes from Baleen DataDescriptions
  baleen-avro-generator/src/main/kotlin/com/shoprunner/baleen/avro/AvroGenerator.kt
  baleen-jsonschema-generator/src/main/kotlin/com/shoprunner/baleen/jsonschema/v3/JsonSchemaGenerator.kt
  baleen-jsonschema-generator/src/main/kotlin/com/shoprunner/baleen/jsonschema/v4/JsonSchemaGenerator.kt
  baleen-kotlin/README.md
  baleen-kotlin/baleen-kotlin-generator/build.gradle
  baleen-kotlin/baleen-kotlin-generator/src/main/kotlin/com/shoprunner/baleen/kotlin/DataClassGenerator.kt
  baleen-kotlin/baleen-kotlin-generator/src/main/kotlin/com/shoprunner/baleen/kotlin/Options.kt
  baleen-kotlin/baleen-kotlin-generator/src/test/kotlin/com/shoprunner/baleen/kotlin/DataClassGeneratorDefaultValuesTest.kt
  baleen-kotlin/baleen-kotlin-generator/src/test/kotlin/com/shoprunner/baleen/kotlin/DataClassGeneratorForNestedModelsTest.kt
  baleen-kotlin/baleen-kotlin-generator/src/test/kotlin/com/shoprunner/baleen/kotlin/DataClassGeneratorForSimpleModelsTest.kt
  baleen-kotlin/baleen-kotlin-generator/src/test/kotlin/com/shoprunner/baleen/kotlin/DataClassGeneratorWithAliasesTest.kt
  baleen-kotlin/baleen-kotlin-generator/src/test/kotlin/com/shoprunner/baleen/kotlin/DataClassGeneratorWriteAndCompileTest.kt
  baleen-xsd-generator/src/main/kotlin/com/shoprunner/baleen/xsd/XsdGenerator.kt
  baleen/src/main/kotlin/com/shoprunner/baleen/types/CoercibleType.kt
  baleen/src/main/kotlin/com/shoprunner/baleen/types/LongCoercibleToType.kt
  baleen/src/main/kotlin/com/shoprunner/baleen/types/StringCoercibleToType.kt
  jsonschema-baleen-generator/src/test/kotlin/com/shoprunner/baleen/jsonschema/v4/BaleenGeneratorTest.kt
  settings.gradle
Labels: enhancement

#87 Upgrade to Gradle 6.0.1
  baleen-xml/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies
